### ISSUE TITLE
Corner leveling not starting in center. 

### ISSUE THREAD

**Issue by Waxonwaxoffmyson** [mikejr83/Marlin-ArtistD#3]
### Bug Description

Start point of bed leveling not in center

### Steps to Reproduce

1. Start level corners in menu

**Expected behavior:** starts in center point

**Actual behavior:** starts bottom left

#### Additional Information

Issue can be corrected with an edit to menu_bed_corners.cpp

* Level corners, starting in the front-left corner.
 */
static int8_t bed_corner;
static inline void _lcd_goto_next_corner() {
  constexpr float lfrb[4] = LEVEL_CORNERS_INSET_LFRB;
  constexpr xy_pos_t lf { (X_MIN_BED) + lfrb[0], (Y_MIN_BED) + lfrb[1] },
                     rb { (X_MAX_BED) - lfrb[2], (Y_MAX_BED) - lfrb[3] };
  line_to_z(LEVEL_CORNERS_Z_HOP);
  switch (bed_corner) {
    case 0: current_position.set(X_CENTER, Y_CENTER); break;
    case 1: current_position   = lf;   break; // copy xy
    case 2: current_position.x = rb.x; break;
    case 3: current_position.y = rb.y; break;
    #if ENABLED(LEVEL_CENTER_TOO)
      case 4: current_position.x = lf.x; break;
    #endif

**Comment by mikejr83** [comment]
@Waxonwaxoffmyson, is this a defect with underlying Marlin? If it is I'll see if it is resolved upstream and will pull that change into my 2.0.7.2 branch. If it isn't then I'll write up the code in the commit and submit it upstream unless you want to submit a PR.

**Comment by mikejr83** [comment]
So I just went and read the code. The Marlin expected behavior is that we start in the LF. We're saying that for the Artist-D we want to redefine the actual functionality. Gotcha.

**Comment by mikejr83** [comment]
Completed.
