### ISSUE TITLE
Posting your source changes...

### ISSUE THREAD

**Issue by Stady234** [mikejr83/Marlin-ArtistD#5]
Can you post your source code, not just your compiled bin file.  I need to do a file compare to locate the bug i have between our two versions....

**Comment by mikejr83** [comment]
Sorry just saw this. The releases I've made are linked to the jgmaker/artistd branch. When I create a release it puts a tag on the commit in the branch to point to that history in time when the release was made. You can then compare that tag with the 2.7.0.2 tag as that is the root from where all my changes started. The 2.7.0.2 tag is the release tagged by Marlin.

**Comment by mikejr83** [comment]
Hey, haven't heard back from you to know if I can help you any more. A couple last ideas that may help you: On the release page you can download the zip to the source as it is at the time of release. This is everything. You can go to https://github.com/mikejr83/Marlin-ArtistD/commits?author=mikejr83 and look at all the changes I've made.

Hope this gets you the info you wanted!
